import 'package:uuid/uuid.dart';

import '../models/ai_assistant_models.dart';
import '../models/chat_message_model.dart';
import '../models/pdf_document_model.dart';
import '../models/question_model.dart';
import '../models/quiz_model.dart';
import 'ai_request_payload_factory.dart';
import 'ai_service.dart';
import 'backend_api_client.dart';
import 'quiz_generation_service.dart';

class RemoteAiService implements AiService {
  RemoteAiService(this._apiClient) : _uuid = const Uuid();

  final BackendApiClient _apiClient;
  final Uuid _uuid;

  @override
  Future<AiAssistantResponse> sendGeneralMessage({
    required String prompt,
    required AiActionType actionType,
    List<ChatMessageModel> history = const <ChatMessageModel>[],
  }) async {
    final json = await _apiClient.postJson(
      '/ai/respond',
      body: AiRequestPayloadFactory.buildGeneralPayload(
        prompt: prompt,
        actionType: actionType,
        history: history,
      ),
    );

    return _parseAssistantResponse(json);
  }

  @override
  Future<AiAssistantResponse> sendPdfMessage({
    required String prompt,
    required PdfDocumentModel document,
    required AiActionType actionType,
    List<ChatMessageModel> history = const <ChatMessageModel>[],
  }) async {
    final json = await _apiClient.postJson(
      '/ai/respond',
      body: AiRequestPayloadFactory.buildPdfPayload(
        prompt: prompt,
        document: document,
        actionType: actionType,
        history: history,
      ),
    );

    return _parseAssistantResponse(json);
  }

  @override
  Future<QuizModel> generateQuiz({
    required QuizGenerationRequest request,
  }) async {
    final json = await _apiClient.postJson(
      '/ai/respond',
      body: AiRequestPayloadFactory.buildQuizPayload(request),
    );

    return _parseQuizResponse(json, request: request);
  }

  @override
  Future<AiAssistantResponse> explainQuizAnswer({
    required PdfDocumentModel document,
    required QuizAnswerExplanationRequest request,
    List<ChatMessageModel> history = const <ChatMessageModel>[],
  }) async {
    final json = await _apiClient.postJson(
      '/ai/respond',
      body: AiRequestPayloadFactory.buildQuizExplanationPayload(
        document: document,
        request: request,
        history: history,
      ),
    );

    return _parseAssistantResponse(json);
  }

  AiAssistantResponse _parseAssistantResponse(Map<String, dynamic> json) {
    return AiAssistantResponse(
      message: json['message'] as String? ?? 'No response returned.',
      citedSnippets: List<String>.from(
        json['citations'] as List? ?? const <String>[],
      ),
      suggestedPrompts: (json['suggested_prompts'] as List? ?? const [])
          .map(
            (prompt) => _parsePrompt(
              Map<String, dynamic>.from(prompt as Map),
            ),
          )
          .toList(),
    );
  }

  QuizModel _parseQuizResponse(
    Map<String, dynamic> json, {
    required QuizGenerationRequest request,
  }) {
    final quiz = Map<String, dynamic>.from(
      json['quiz'] as Map? ?? const <String, dynamic>{},
    );
    final questionList = (quiz['questions'] as List? ?? const [])
        .map(
          (question) => _parseQuestion(
            Map<String, dynamic>.from(question as Map),
          ),
        )
        .toList();

    return QuizModel(
      id: _uuid.v4(),
      title: quiz['quiz_title'] as String? ?? 'Generated Quiz',
      sourcePdfId: request.sourcePdfId,
      sourcePdfName: request.sourcePdfName,
      sourcePdfText: request.pdfText,
      questions: questionList,
      createdAt: DateTime.now(),
      difficulty: _difficultyLabel(
        quiz['difficulty'] as String? ?? request.difficulty,
      ),
      summary:
          'Generated by the shared Groq assistant using grounded PDF context and exact per-type counts.',
    );
  }

  AiPromptSuggestion _parsePrompt(Map<String, dynamic> json) {
    final rawActionType = json['action_type'] as String? ?? AiActionType.ask.name;
    return AiPromptSuggestion(
      label: json['label'] as String? ?? 'Ask follow-up',
      prompt: json['prompt'] as String? ?? '',
      actionType: AiActionType.values.firstWhere(
        (value) => value.name == rawActionType,
        orElse: () => AiActionType.ask,
      ),
    );
  }

  QuestionModel _parseQuestion(Map<String, dynamic> json) {
    final rawType = json['type'] as String? ?? 'short_answer';

    return QuestionModel(
      id: _uuid.v4(),
      type: _mapQuestionType(rawType),
      prompt: json['question'] as String? ?? 'Untitled question',
      answer: json['answer'] as String? ?? '',
      choices: List<String>.from(json['options'] as List? ?? const <String>[]),
      explanation: json['explanation'] as String?,
    );
  }

  QuestionType _mapQuestionType(String rawType) {
    switch (rawType) {
      case 'multiple_choice':
        return QuestionType.multipleChoice;
      case 'true_false':
        return QuestionType.trueFalse;
      case 'identification':
        return QuestionType.identification;
      case 'short_answer':
      default:
        return QuestionType.shortAnswer;
    }
  }

  String _difficultyLabel(String difficulty) {
    switch (difficulty.toLowerCase()) {
      case 'easy':
        return 'Easy';
      case 'hard':
        return 'Hard';
      default:
        return 'Medium';
    }
  }
}
