import 'package:uuid/uuid.dart';

import '../models/question_model.dart';
import '../models/quiz_model.dart';
import 'ai_request_payload_factory.dart';
import 'backend_api_client.dart';
import 'quiz_generation_service.dart';

class RemoteQuizGenerationService implements QuizGenerationService {
  RemoteQuizGenerationService(this._apiClient) : _uuid = const Uuid();

  final BackendApiClient _apiClient;
  final Uuid _uuid;

  @override
  Future<QuizModel> generateQuizFromText(QuizGenerationRequest request) async {
    final json = await _apiClient.postJson(
      '/quiz/generate',
      body: AiRequestPayloadFactory.buildQuizPayload(request),
    );

    final quiz = Map<String, dynamic>.from(
      json['quiz'] as Map? ?? const <String, dynamic>{},
    );
    final questionList = (quiz['questions'] as List? ?? const [])
        .map(
          (question) => _parseQuestion(
            Map<String, dynamic>.from(question as Map),
          ),
        )
        .toList();

    return QuizModel(
      id: _uuid.v4(),
      title: quiz['quiz_title'] as String? ?? 'Generated Quiz',
      sourcePdfId: request.sourcePdfId,
      sourcePdfName: request.sourcePdfName,
      sourcePdfText: request.pdfText,
      questions: questionList,
      createdAt: DateTime.now(),
      difficulty: _difficultyLabel(
        quiz['difficulty'] as String? ?? request.difficulty,
      ),
      summary:
          'Generated by the Groq backend using strict JSON output and exact per-type counts.',
    );
  }

  QuestionModel _parseQuestion(Map<String, dynamic> json) {
    final rawType = json['type'] as String? ?? 'short_answer';

    return QuestionModel(
      id: _uuid.v4(),
      type: _mapQuestionType(rawType),
      prompt: json['question'] as String? ?? 'Untitled question',
      answer: json['answer'] as String? ?? '',
      choices: List<String>.from(json['options'] as List? ?? const <String>[]),
      explanation: json['explanation'] as String?,
    );
  }

  QuestionType _mapQuestionType(String rawType) {
    switch (rawType) {
      case 'multiple_choice':
        return QuestionType.multipleChoice;
      case 'true_false':
        return QuestionType.trueFalse;
      case 'identification':
        return QuestionType.identification;
      case 'short_answer':
      default:
        return QuestionType.shortAnswer;
    }
  }

  String _difficultyLabel(String difficulty) {
    switch (difficulty.toLowerCase()) {
      case 'easy':
        return 'Easy';
      case 'hard':
        return 'Hard';
      default:
        return 'Medium';
    }
  }
}
